[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  publish = "dist"

  # Default build command.
  command = "npm run generate && cp -r photos dist/photos"

[build.environment]
NODE_VERSION = "18"